name: Build EIV_DataPack.Console

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    # allows manual trigger

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: ${{ secrets.EIV_NUGET }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GH_READ_NUGET }}
    - name: Publish
      run: dotnet publish EIV_DataPack.Console/EIV_DataPack.ConsoleApp.csproj /p:PublishProfile=ReleaseLinux
    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v4
      with:
        name: EIV_DataPack.ConsoleApp-Linux
        path: Out/Linux
        if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: ${{ secrets.EIV_NUGET }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GH_READ_NUGET }}
    - name: Publish
      run: dotnet publish EIV_DataPack.Console/EIV_DataPack.ConsoleApp.csproj /p:PublishProfile=ReleaseWin
    - name: Upload artifact (Win)
      uses: actions/upload-artifact@v4
      with:
        name: EIV_DataPack.ConsoleApp-Win
        path: Out/Win
        if-no-files-found: error
